/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as MeetingsCodeRouteImport } from './routes/meetings.$code'
import { Route as AuthenticatedSigRouteImport } from './routes/_authenticated.sig'
import { Route as AuthenticatedPatrimoineRouteImport } from './routes/_authenticated.patrimoine'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated.finances'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAdministrationRouteImport } from './routes/_authenticated.administration'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsCodeRoute = MeetingsCodeRouteImport.update({
  id: '/meetings/$code',
  path: '/meetings/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSigRoute = AuthenticatedSigRouteImport.update({
  id: '/sig',
  path: '/sig',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatrimoineRoute = AuthenticatedPatrimoineRouteImport.update({
  id: '/patrimoine',
  path: '/patrimoine',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdministrationRoute =
  AuthenticatedAdministrationRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/administration': typeof AuthenticatedAdministrationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/patrimoine': typeof AuthenticatedPatrimoineRoute
  '/sig': typeof AuthenticatedSigRoute
  '/meetings/$code': typeof MeetingsCodeRoute
  '/verify/$code': typeof VerifyCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/administration': typeof AuthenticatedAdministrationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/patrimoine': typeof AuthenticatedPatrimoineRoute
  '/sig': typeof AuthenticatedSigRoute
  '/meetings/$code': typeof MeetingsCodeRoute
  '/verify/$code': typeof VerifyCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/administration': typeof AuthenticatedAdministrationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRoute
  '/_authenticated/patrimoine': typeof AuthenticatedPatrimoineRoute
  '/_authenticated/sig': typeof AuthenticatedSigRoute
  '/meetings/$code': typeof MeetingsCodeRoute
  '/verify/$code': typeof VerifyCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/administration'
    | '/dashboard'
    | '/finances'
    | '/patrimoine'
    | '/sig'
    | '/meetings/$code'
    | '/verify/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/administration'
    | '/dashboard'
    | '/finances'
    | '/patrimoine'
    | '/sig'
    | '/meetings/$code'
    | '/verify/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/administration'
    | '/_authenticated/dashboard'
    | '/_authenticated/finances'
    | '/_authenticated/patrimoine'
    | '/_authenticated/sig'
    | '/meetings/$code'
    | '/verify/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeetingsCodeRoute: typeof MeetingsCodeRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/$code': {
      id: '/meetings/$code'
      path: '/meetings/$code'
      fullPath: '/meetings/$code'
      preLoaderRoute: typeof MeetingsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sig': {
      id: '/_authenticated/sig'
      path: '/sig'
      fullPath: '/sig'
      preLoaderRoute: typeof AuthenticatedSigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patrimoine': {
      id: '/_authenticated/patrimoine'
      path: '/patrimoine'
      fullPath: '/patrimoine'
      preLoaderRoute: typeof AuthenticatedPatrimoineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administration': {
      id: '/_authenticated/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AuthenticatedAdministrationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdministrationRoute: typeof AuthenticatedAdministrationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRoute
  AuthenticatedPatrimoineRoute: typeof AuthenticatedPatrimoineRoute
  AuthenticatedSigRoute: typeof AuthenticatedSigRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdministrationRoute: AuthenticatedAdministrationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinancesRoute: AuthenticatedFinancesRoute,
  AuthenticatedPatrimoineRoute: AuthenticatedPatrimoineRoute,
  AuthenticatedSigRoute: AuthenticatedSigRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  MeetingsCodeRoute: MeetingsCodeRoute,
  VerifyCodeRoute: VerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
